# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |
    echo sudo
    sudo apt update
    sudo apt install gnupg ca-certificates curl wget software-properties-common apt-transport-https lsb-release -y
    curl -sL https://packages.microsoft.com/keys/microsoft.asc |
    gpg --dearmor |
    sudo tee /etc/apt/trusted.gpg.d/microsoft.asc.gpg > /dev/null
    sudo add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/18.04/prod.list)"
    sudo apt update
    sudo apt install -y azdata-cli mssql-tools
  displayName: 'install azdata'

- script: azdata --version
  displayName: 'check azdata version'

- script: /opt/mssql-tools/bin/sqlcmd -?
  displayName: 'check sqlcmd version'

- script: |
    docker run -e 'ACCEPT_EULA=Y' -e 'MSSQL_SA_PASSWORD=StrongPASSWORD1' --name 'sql1' -p 1433:1433 -d mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
  displayName: 'dummy test with mssql'

- script: /opt/mssql-tools/bin/sqlcmd -U$(USERNAME) -P$(PASSWORD) -Slocalhost -Q "Select @@version"
  displayName: 'sample query'


